export {default as Honors } from './Honors/Honors'
export {default as UsefulLinks } from './UsefulLinks/UsefulLinks'
export {default as About } from './About/About'
export {default as Trusts } from './Trusts/Trusts'
export {default as Copyright } from './Copyright/Copyright'
