export {default as homeReducer} from './homeSlice'
export {default as productReducer} from './productSlice'
export {default as categoryReducer} from './categorySlice'
export {default as searchReducer} from './searchSlice'
export {default as cartReducer} from './cartSlice'
export {default as mainReducer} from './mainSlice'